### ISSUE TITLE
Add some input validation

### ISSUE THREAD

**Issue by geektortoise** [Cytomine-ULiege/S_Segment-CV-AdaptThres-Sample#1]
Hello, 
I got the following error when setting 400 for the "Threshold block size" : 

OpenCV(4.2.0) /io/opencv/modules/imgproc/src/thresh.cpp:1648: error: (-215:Assertion failed) blockSize % 2 == 1 && blockSize > 1 in function 'adaptiveThreshold' 

I guess this value must be odd and > 1.

The result is correctly returned and visible in a Cytomine instance but I wonder if an aesthetic error would be better.

Possible solutions
- add a +1 if the value is even
or
- catch the error and throw a new one with a more simple message for the end user.

Have a nice day.

**Comment by urubens** [comment]
I'm in favor of the `a+1` solution with a warning in logs. 
Less frustration for end users if the app is able to recover simple parameters issues IMHO :smiley:
